import numpy as np
import pandas as pd
import pytest

from oil_futures_regime.common_trend import (
    cts_state_summary,
    filtered_states,
    fit_cts_model,
    simulate_cts_paths,
)
from oil_futures_regime.regimes import prepare_residual_pool
from oil_futures_regime.scenario_models import SIMULATORS, common_uniforms, simulate


def common_trend_panel(n=520, phi=0.85, sigma_eta=0.03, sigma_nu=0.02,
                       sigma_eps=0.003, mu=0.001, seed=17):
    """Data generated by exactly the model under test, so parameters are known."""
    rng = np.random.default_rng(seed)
    tau = np.cumsum(mu + rng.normal(0, sigma_eta, n)) + 4.2
    s = np.zeros(n)
    for t in range(1, n):
        s[t] = phi * s[t - 1] + rng.normal(0, sigma_nu)
    idx = pd.date_range("2013-01-04", periods=n, freq="W-FRI")
    return pd.DataFrame(
        {
            "WTI": tau + 0.5 * s + rng.normal(0, sigma_eps, n),
            "BRENT": tau - 0.5 * s + rng.normal(0, sigma_eps, n),
        },
        index=idx,
    ), pd.Series(s, index=idx)


def _pool(model, mode="equal"):
    return prepare_residual_pool(model.residuals, mode=mode)


def test_parameters_are_recovered_on_data_from_the_model():
    Y, _ = common_trend_panel()
    m = fit_cts_model(Y)
    assert m.params["phi"] == pytest.approx(0.85, abs=0.15)
    assert m.params["sigma_eta"] == pytest.approx(0.03, rel=0.35)
    assert m.params["sigma_nu"] == pytest.approx(0.02, rel=0.6)
    assert 0.0 < m.params["phi"] < 1.0


def test_filtered_spread_tracks_the_latent_state():
    Y, latent = common_trend_panel()
    m = fit_cts_model(Y)
    fs = filtered_states(m, Y.index)
    corr = np.corrcoef(fs["spread_filtered"].values, latent.values[: len(fs)])[0, 1]
    assert corr > 0.9
    # The filtered spread is a smoothed version of the noisy observed spread.
    observed = (Y["WTI"] - Y["BRENT"]).values[: len(fs)]
    assert fs["spread_filtered"].std() <= observed.std() * 1.05


def test_implied_beta_matches_the_cointegrating_vector():
    Y, _ = common_trend_panel()
    summary = cts_state_summary(fit_cts_model(Y, restrict_trend=True))
    assert np.allclose(summary["beta_implied"], np.array([1.0, -1.0]))
    assert summary["spread_half_life_weeks"] > 0
    assert np.isfinite(summary["spread_uncond_sd"])


def test_free_trend_loading_stays_near_one_for_wti_brent_like_data():
    Y, _ = common_trend_panel()
    m = fit_cts_model(Y, restrict_trend=False)
    assert m.params["trend_loading_brent"] == pytest.approx(1.0, abs=0.1)


def test_standardized_innovations_have_unit_scale():
    Y, _ = common_trend_panel()
    m = fit_cts_model(Y)
    sd = m.residuals.std().values
    assert np.all(np.abs(sd - 1.0) < 0.25)
    corr = np.corrcoef(m.residuals.values.T)[0, 1]
    assert abs(corr) < 0.35  # the Cholesky rotation removes contemporaneous dependence


def test_simulation_is_reproducible_and_starts_from_the_last_price():
    Y, _ = common_trend_panel()
    m = fit_cts_model(Y)
    pool, prob, _ = _pool(m)
    u = common_uniforms(8, 256, seed=4)
    x1 = simulate_cts_paths(m, pool, prob, horizon=8, n_sim=256, u=u)
    x2 = simulate(m, pool, prob, horizon=8, n_sim=256, u=u)   # via the registry
    assert x1.shape == (9, 256, 2)
    assert np.allclose(x1, x2)
    assert np.allclose(x1[0, 0, :], m.last_log_price)
    assert np.isfinite(x1).all()


def test_cts_is_registered_in_the_dispatch_table():
    assert "CTS" in SIMULATORS


def test_simulated_spread_mean_reverts_while_the_level_diffuses():
    Y, _ = common_trend_panel()
    m = fit_cts_model(Y)
    pool, prob, _ = _pool(m)
    u = common_uniforms(40, 3000, seed=6)
    p = simulate_cts_paths(m, pool, prob, horizon=40, n_sim=3000, u=u)

    level_sd_short = p[1, :, 0].std()
    level_sd_long = p[40, :, 0].std()
    spread_sd_short = (p[1, :, 0] - p[1, :, 1]).std()
    spread_sd_long = (p[40, :, 0] - p[40, :, 1]).std()

    # The common trend is integrated: level dispersion keeps growing.
    assert level_sd_long > 3.0 * level_sd_short
    # The relative component is stationary: spread dispersion converges.
    assert spread_sd_long < 2.5 * spread_sd_short
    assert spread_sd_long < 0.5 * level_sd_long


def test_forecast_spread_converges_towards_zero_from_a_dislocation():
    Y, _ = common_trend_panel()
    # Push the last observations apart so the filtered spread starts wide.
    Y = Y.copy()
    Y.iloc[-3:, 0] += 0.12
    m = fit_cts_model(Y)
    pool, prob, _ = _pool(m)
    u = common_uniforms(40, 3000, seed=8)
    p = simulate_cts_paths(m, pool, prob, horizon=40, n_sim=3000, u=u)

    start_spread = abs(np.median(p[1, :, 0] - p[1, :, 1]))
    end_spread = abs(np.median(p[40, :, 0] - p[40, :, 1]))
    assert end_spread < start_spread


def test_free_and_restricted_models_are_distinct_families():
    Y, _ = common_trend_panel()
    r = fit_cts_model(Y, restrict_trend=True)
    f = fit_cts_model(Y, restrict_trend=False)
    assert r.family == "CTS" and f.family == "CTSF"
    assert r.restricted is True and f.restricted is False
    assert "CTSF" in SIMULATORS


def test_restriction_bias_shows_up_when_the_loading_is_not_one():
    """If the true trend loading differs from 1, forcing it inflates persistence.

    This is the mechanism behind the contaminated spread half-life on real data:
    a mis-specified beta leaves part of a near-unit-root trend inside the
    'relative' component.
    """
    rng = np.random.default_rng(23)
    n, a_true, phi = 520, 1.05, 0.80
    tau = np.cumsum(0.001 + rng.normal(0, 0.03, n)) + 4.2
    s = np.zeros(n)
    for t in range(1, n):
        s[t] = phi * s[t - 1] + rng.normal(0, 0.02)
    idx = pd.date_range("2013-01-04", periods=n, freq="W-FRI")
    Y = pd.DataFrame({"WTI": tau + 0.5 * s + rng.normal(0, 0.003, n),
                      "BRENT": a_true * tau - 0.5 * s + rng.normal(0, 0.003, n)}, index=idx)

    restricted = fit_cts_model(Y, restrict_trend=True)
    free = fit_cts_model(Y, restrict_trend=False)

    assert free.params["trend_loading_brent"] == pytest.approx(a_true, abs=0.05)
    # The restricted fit attributes trend persistence to the relative component.
    assert restricted.params["phi"] > free.params["phi"]
    assert abs(free.params["phi"] - phi) < abs(restricted.params["phi"] - phi)
